[github_app]
handle_pr_actions = ['opened', 'reopened', 'ready_for_review', 'review_requested']
pr_commands = [
  "/describe",
  "/review",
]
handle_push_trigger = true
push_commands = [
  "/describe --pr_description.add_original_user_description=true --pr_description.keep_original_user_title=true --pr_description.use_description_markers=true",
  "/review -i --pr_reviewer.remove_previous_review_comment=true",
]

[pr_description]
use_description_markers=true

[config]
verbosity_level=2
