[pr_reviewer]
enable_review_labels_effort = true


[pr_code_suggestions]
summarize=true

[github_app]
handle_push_trigger = true
push_trigger_ignore_bot_commits = true
push_trigger_ignore_merge_commits = true
push_trigger_wait_for_initial_review = true
push_trigger_pending_tasks_backlog = true
push_trigger_pending_tasks_ttl = 300
push_commands = [
    "/describe --pr_description.add_original_user_description=true --pr_description.keep_original_user_title=true",
    """/auto_review -i \
       --pr_reviewer.require_focused_review=false \
       --pr_reviewer.require_score_review=false \
       --pr_reviewer.require_tests_review=false \
       --pr_reviewer.require_security_review=false \
       --pr_reviewer.require_estimate_effort_to_review=false \
       --pr_reviewer.num_code_suggestions=0 \
       --pr_reviewer.inline_code_comments=false \
       --pr_reviewer.remove_previous_review_comment=true \
       --pr_reviewer.require_all_thresholds_for_incremental_review=false \
       --pr_reviewer.minimal_commits_for_incremental_review=1 \
       --pr_reviewer.minimal_minutes_for_incremental_review=1 \
       --pr_reviewer.extra_instructions='' \
    """
]
