[pr_reviewer]
enable_review_labels_effort = true


[pr_code_suggestions]
summarize=true

[github_app]
handle_push_trigger = true
push_commands = [
    "/describe --pr_description.add_original_user_description=true --pr_description.keep_original_user_title=true",
    "/auto_review -i --pr_reviewer.remove_previous_review_comment=true",
    "/auto_improve",
]
