name: Refactor Code
title: 'Refactor: '
description: Document the refactoring process for a specific component in a PR
labels: refactor
body:
  - type: textarea
    id: refactor_description
    attributes:
      label: Refactor Details
      description: Detailed description of the refactoring process
      placeholder: We are refactoring this component because ...
